repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      # - id: check-json
      #   exclude: ^.devcontainer/devcontainer.json
      # - id: pretty-format-json
      #   exclude: ^.devcontainer/devcontainer.json
      #   args: [--autofix, --no-sort-keys]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.392
    hooks:
      - id: pyright

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.5"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix, --show-fixes]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier

exclude: "copilot/"
